services:
  backend:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - tf-serving
    networks:
      - app-net
    environment:
      - TF_SERVING_BASE_URL=http://tf-serving:8501
      - MODEL_NAME=smile
      - FRONTEND_ADDR=http://localhost:3000
      - PATH_TO_SUPERVISED_RESULTS=model/results/supervised.json
      - PATH_TO_UNSUPERVISED_RESULTS=model/results/unsupervised.json

  tf-serving:
    image: tensorflow/serving
    ports:
      - "8501:8501"
    networks:
      - app-net
    volumes:
      - ./model/smile_detector:/models/smile
    environment:
      - MODEL_NAME=smile

networks:
  app-net:
